from django.urls import path
from .views import *

urlpatterns = [
    
    path('', login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('customers/', customer_management, name='customer_management'),
    path('companies/', company_management, name='company_management'),
     path('companies/update/<int:company_id>/', update_company, name='update_company'),
     path('companies/delete/<int:company_id>/', delete_company, name='delete_company'),
     path('customers/update/<int:customer_id>/', update_customer, name='update_customer'),
    path('customers/delete/<int:customer_id>/', delete_customer, name='delete_customer'),
    path('dashboard/', dashboard, name='dashboard'),
    path('users/', user_list, name='user_list'),
    path('users/add/', add_user, name='add_user'),
    path('users/update/<int:user_id>/', update_user, name='update_user'),
    path('users/delete/<int:user_id>/', delete_user, name='delete_user'),
    path('subscription-plans/', subscription_plan_management, name='subscription_plan_management'),
    path('subscription-plans/update/<int:plan_id>/', update_subscription_plan, name='update_subscription_plan'),
    path('subscription-plans/delete/<int:plan_id>/', delete_subscription_plan, name='delete_subscription_plan'),
    path('billing/', billing_management, name='billing_management'),
    path('states/', state_list, name='state_list'),
    path('states/add/', add_state, name='add_state'),
    path('states/update/<int:state_id>/', update_state, name='update_state'),
    path('states/delete/<int:state_id>/', delete_state, name='delete_state'),
    path('cities/', city_list, name='city_list'),
    path('cities/add/', add_city, name='add_city'),
    path('cities/update/<int:city_id>/', update_city, name='update_city'),
    path('cities/delete/<int:city_id>/', delete_city, name='delete_city'),
    path('areas/', area_list, name='area_list'),
    path('areas/add/', add_area, name='add_area'),
    path('areas/update/<int:area_id>/', update_area, name='update_area'),
    path('areas/delete/<int:area_id>/', delete_area, name='delete_area'),
    path("api/cities/<int:state_id>/", get_cities, name="api_get_cities"),
    path("api/areas/<int:city_id>/", get_areas, name="api_get_areas"),
    path('customer/locations/<int:customer_id>/', customer_locations, name='customer_locations'),
    path('customers_location/update/<int:location_id>/', update_customer_location, name='update_customer_location'),
    path('customers_location/delete/<int:location_id>/', delete_customer_location, name='delete_customer_location'),
    path('company/locations/<int:company_id>/', company_locations, name='company_locations'),
    path('company_location/update/<int:location_id>/', update_company_location, name='update_company_location'),
    path('company_location/delete/<int:location_id>/', delete_company_location, name='delete_company_location'),
    path('settings/', settings_view, name='settings_view'),
    path('organizations/', organization_details, name='organization_management'),
    path('reports/', reports, name='reports'),
    path('customers/bulk-upload/', bulk_upload_customers, name='bulk_upload_customers'),
    path('export/companies/', export_companies_excel, name='export_companies'),
    path('export/customers/', export_customers_excel, name='export_all_customers'),
    path('export/customers/active/', export_customers_excel, {'status': 'active'}, name='export_active_customers'),
    path('export/customers/inactive/', export_customers_excel, {'status': 'inactive'}, name='export_inactive_customers'),
    path('export/invoices/', export_invoices_excel, name='export_invoices'),
    path('export/financial/total/', export_financial_summary_excel, {'report_type': 'total_amount'}, name='export_total_amount'),
    path('export/financial/collected/', export_financial_summary_excel, {'report_type': 'collected'}, name='export_collected'),
    path('export/financial/outstanding/', export_financial_summary_excel, {'report_type': 'outstanding'}, name='export_outstanding'),
    path('billing-records/bulk-upload/', bulk_upload_billing_records, name='bulk_upload_billing_records'),
    path('manual-billing/', manual_billing_view, name='manual_billing'),
    path('get-entity-billing-details/', get_entity_billing_details, name='get_entity_billing_details'),
    path('analytics/', subscription_analytics_form, name='analytics'),
    path('lock-filters/',lock_filters, name='lock_filters'),
    path('validate-filter-password/', validate_filter_password, name='validate_filter_password'),
    path('api/lock-filters/', lock_filters, name='lock_filters'),
    path('create/', create_billing, name='create_billing'),
    path('analytics/report/', subscription_analytics_report, name='subscription_analytics_report'),
    path('api/get-locations/', get_locations, name='get_locations'),
    path('forgot-password/', forgot_password, name='forgot_password'),
    path('verify-otp/', verify_otp, name='verify_otp'),
    path('reset-password/', reset_password, name='reset_password'),
    path('active_customers_list/', active_customers_list, name='active_customers_list'),
    path('inactive_customers_list/', inactive_customers_list, name='inactive_customers_list'),
    path('billing/api/get-locations/', get_billing_locations, name='get_billing_locations'),
    path('non_gst', company_gst, name='company_gst'),
    path('api/get-companies/', get_companies, name='get_companies'),
    path('api/update-company-filter/', update_company_filter, name='update_company_filter'),
    path('api/session-diagnostic/', session_diagnostic, name='session_diagnostic'),
    path('reports/financial-sales/', 
         financial_sales_report_view, 
         name='financial_sales_report'),
    
    path('reports/financial-sales/export-pdf/', 
         export_financial_sales_pdf, 
         name='export_financial_sales_pdf'),
    
    path('reports/financial-sales/export-excel/', 
         export_financial_sales_excel, 
         name='export_financial_sales_excel'),
     path('roles/', role_list, name='role_list'),
    path('roles/add/', add_role, name='add_role'),
    path('roles/update/<int:role_id>/', update_role, name='update_role'),
    path('roles/delete/<int:role_id>/', delete_role, name='delete_role'),
    
    path('role_permissions/<int:role_id>/', role_permissions, name='role_permissions'),
    path('api/validate-filter-password/', validate_filter_password, name='validate_filter_password'),
    path('api/get-companies/', get_companies, name='get_companies'),
    path('api/update-company-filter/', update_company_filter, name='update_company_filter'),
    path('payments/approval-list/', payment_approval_list, name='payment_approval_list'),
    path('payments/bulk-approve/', bulk_approve_payments, name='bulk_approve_payments'),
    path('payments/<int:payment_id>/approve/', approve_single_payment, name='approve_single_payment'),
    path('user-activity-logs/', user_activity_logs_report, name='user_activity_logs'),
    path(
        'customers/<int:customer_id>/locations/bulk-upload/',
        bulk_upload_locations,
        name='bulk_upload_locations',
    ),
    path('customers/bulk-upload-combined/', bulk_upload_customers_and_locations, name='bulk_upload_combined'),
path('customers/template/combined/', download_combined_customer_template, name='download_combined_template'),
path('payments/export-approvals/',
         export_payment_approval_excel,
         name='export_payment_approvals'),
    path('payments/<int:log_id>/edit-approval/',  edit_payment_approval,  name='edit_payment_approval'),
    path('payments/<int:log_id>/delete-approval/',delete_payment_approval,name='delete_payment_approval'),
   

]