# Generated by Django 5.2.8 on 2025-12-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_customerlocation_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlocation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
