# Generated by Django 5.2.8 on 2025-12-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_customerlocation_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
