# Generated by Django 5.2.8 on 2025-12-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_company_contact_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylocation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.subscriptionplan'),
        ),
    ]
