# Generated by Django 5.2.8 on 2025-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_companylocation_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
