# Generated by Django 5.2.8 on 2025-12-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_company_location_link_companylocation_location_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_2',
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='App1.customer')),
            ],
        ),
    ]
