# Generated by Django 5.2.8 on 2025-12-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_remove_customer_contact_remove_customer_contact_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
