# Generated by Django 5.2.8 on 2025-12-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_customer_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
