# Generated by Django 5.2.8 on 2025-12-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_company_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylocation',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
