# Generated by Django 5.2.8 on 2025-12-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_customer_company_customer_cameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
