# Generated by Django 5.2.8 on 2025-12-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_customer_tax_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
