# Generated by Django 5.2.8 on 2025-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
