# Generated by Django 5.2.8 on 2025-12-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cusstomer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.custom_user')),
            ],
        ),
    ]
