# Generated by Django 5.2.8 on 2025-12-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_data_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_logs',
            old_name='cusstomer',
            new_name='customer',
        ),
    ]
