# Generated by Django 5.2.8 on 2025-12-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_rename_cusstomer_data_logs_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_logs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.custom_user'),
        ),
    ]
