# Generated by Django 5.2.8 on 2025-12-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_alter_data_logs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
