# Generated by Django 5.2.8 on 2025-12-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0018_customer_advance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
