# Generated by Django 5.2.8 on 2025-12-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_organization_cin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
