# Generated by Django 5.2.8 on 2026-01-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0020_remove_custom_user_roles_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='App1.billingrecord')),
            ],
            options={
                'verbose_name': 'Bill Item',
                'verbose_name_plural': 'Bill Items',
                'ordering': ['id'],
            },
        ),
    ]
