# Generated by Django 5.2.8 on 2026-01-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0021_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
