# Generated by Django 5.2.8 on 2026-01-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0022_billingrecord_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_logs',
            name='billing_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.billingrecord'),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.company'),
        ),
    ]
