# Generated by Django 5.2.8 on 2026-01-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0023_data_logs_billing_record_data_logs_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
