# Generated by Django 5.2.8 on 2026-01-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0025_data_logs_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='billing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='billing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
