# Generated by Django 5.2.8 on 2026-01-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0026_billingrecord_billing_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_logs',
            name='company',
        ),
        migrations.AddField(
            model_name='data_logs',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.customerlocation'),
        ),
    ]
