# Generated by Django 5.2.8 on 2026-01-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0027_remove_data_logs_company_data_logs_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlocation',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='data_logs',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
