# Generated by Django 5.2.8 on 2026-01-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0028_remove_customerlocation_subscription_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='customerlocation',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.subscriptionplan'),
        ),
    ]
