# Generated by Django 5.2.8 on 2026-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0029_remove_company_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
