# Generated by Django 5.2.8 on 2026-01-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0030_billingrecord_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrecord',
            name='company',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='company_location',
        ),
    ]
