# Generated by Django 5.2.8 on 2026-01-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0031_remove_billingrecord_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
