# Generated by Django 5.2.8 on 2026-02-03 07:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0032_company_account_number_company_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='billing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_v', models.BooleanField(default=False)),
                ('customer_management_v', models.BooleanField(default=False)),
                ('customer_management_a', models.BooleanField(default=False)),
                ('customer_management_e', models.BooleanField(default=False)),
                ('customer_management_d', models.BooleanField(default=False)),
                ('company_master_v', models.BooleanField(default=False)),
                ('company_master_a', models.BooleanField(default=False)),
                ('company_master_e', models.BooleanField(default=False)),
                ('company_master_d', models.BooleanField(default=False)),
                ('subscription_master_v', models.BooleanField(default=False)),
                ('subscription_master_a', models.BooleanField(default=False)),
                ('subscription_master_e', models.BooleanField(default=False)),
                ('subscription_master_d', models.BooleanField(default=False)),
                ('billing_invoices_v', models.BooleanField(default=False)),
                ('billing_invoices_a', models.BooleanField(default=False)),
                ('billing_invoices_e', models.BooleanField(default=False)),
                ('billing_invoices_d', models.BooleanField(default=False)),
                ('roles_v', models.BooleanField(default=False)),
                ('roles_a', models.BooleanField(default=False)),
                ('roles_e', models.BooleanField(default=False)),
                ('roles_d', models.BooleanField(default=False)),
                ('users_v', models.BooleanField(default=False)),
                ('users_a', models.BooleanField(default=False)),
                ('users_e', models.BooleanField(default=False)),
                ('users_d', models.BooleanField(default=False)),
                ('manual_receipts_v', models.BooleanField(default=False)),
                ('reports_v', models.BooleanField(default=False)),
                ('data_logs_v', models.BooleanField(default=False)),
                ('settings_v', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='App1.roles')),
            ],
        ),
        migrations.AddField(
            model_name='custom_user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.roles'),
        ),
    ]
