# Generated by Django 5.2.8 on 2026-02-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0033_roles_alter_billingrecord_billing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='gst_type',
            field=models.CharField(choices=[('INTRA-STATE', 'Intra-State (CGST + SGST)'), ('INTER-STATE', 'Inter-State (IGST)'), ('NONE', 'No GST')], default='NONE', max_length=20),
        ),
    ]
