# Generated by Django 5.2.8 on 2026-02-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0034_billingrecord_gst_amount_billingrecord_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom amount that overrides the default subscription plan price', max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerContact',
        ),
    ]
