# Generated by Django 5.2.8 on 2026-02-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0036_customercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='previous_subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_customers', to='App1.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='upgrade_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='is_upgrade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='new_subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_plan_logs', to='App1.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='old_subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_plan_logs', to='App1.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='upgrade_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
