# Generated by Django 5.2.8 on 2026-02-08 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0037_customer_previous_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_logs',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Data Log', 'verbose_name_plural': 'Data Logs'},
        ),
        migrations.AddField(
            model_name='data_logs',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_logs', to='App1.custom_user'),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Payment has been approved'),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='is_payment',
            field=models.BooleanField(default=False, help_text='Indicates this is a payment entry'),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Payment needs approval'),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payment_logs', to='App1.custom_user'),
        ),
        migrations.AddField(
            model_name='data_logs',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
