# Generated by Django 5.2.8 on 2026-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0038_alter_data_logs_options_data_logs_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_logs',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='data_logs',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='data_logs',
            name='requires_approval',
        ),
        migrations.AlterField(
            model_name='data_logs',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_logs',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
