# Generated by Django 5.2.8 on 2026-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0039_alter_data_logs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
