# Generated by Django 5.2.8 on 2026-02-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0040_alter_billingrecord_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissions',
            name='payment_approval_e',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='payment_approval_v',
            field=models.BooleanField(default=False),
        ),
    ]
