# Generated by Django 5.2.8 on 2026-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0041_rolepermissions_payment_approval_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='outstanding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
