# Generated by Django 5.2.8 on 2026-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0042_customer_outstanding_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlocation',
            name='custom_subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom amount that overrides the default subscription plan price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
