# Generated by Django 5.2.8 on 2026-02-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0043_customerlocation_custom_subscription_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_date', models.DateField()),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.custom_user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_changes', to='App1.customer')),
                ('customer_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_changes', to='App1.customerlocation')),
                ('new_subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_changes', to='App1.subscriptionplan')),
                ('old_subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_changes', to='App1.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Change',
                'verbose_name_plural': 'Subscription Changes',
                'ordering': ['-change_date'],
            },
        ),
    ]
