# Generated by Django 5.2.8 on 2026-02-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0045_user_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissions',
            name='user_logs_v',
            field=models.BooleanField(default=False),
        ),
    ]
