# Generated by Django 5.2.8 on 2026-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0046_rolepermissions_user_logs_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
