# Generated by Django 5.2.8 on 2026-02-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0047_billingrecord_balance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlocation',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST registration number (required if gst_registered is True)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='gst_registered',
            field=models.BooleanField(default=False, help_text='Whether this location is GST registered'),
        ),
    ]
