# Generated by Django 5.2.8 on 2026-02-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0048_customerlocation_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_logs',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
