# Generated by Django 5.2.8 on 2026-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0049_data_logs_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissions',
            name='manual_receipts_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='payment_approval_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='payment_approval_d',
            field=models.BooleanField(default=False),
        ),
    ]
