# Generated by Django 5.2.8 on 2026-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0050_rolepermissions_manual_receipts_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_logs',
            name='discount_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
